Farms module
mauriciofer/agrohawk-erp pull request #7
Opened 2021-04-07 20:36 UTC by SolGarCR

2021-04-08 15:20 UTC, mauriciofer requested changes

2021-04-18 00:40 UTC, SolGarCR commented on pages/farms/index.vue
> +            <small
Deje este por que pienso q los campos que tienen ese * si son requeridos

2021-04-18 02:52 UTC, mauriciofer commented on pages/farms/index.vue
> +            <small
Si correcto

2021-04-19 05:18 UTC, reynaldoguerrero approved these changes

2021-05-02 17:43 UTC, mauriciofer approved these changes

2021-05-02 17:44 UTC, merged